import "./src/crossword.js";

const crossword = document.createElement("crossword-app");

// crossword.data = {
//   id: "crosswords/example/1",
//   title: "example crossword 1",
//   size: "5x5",
//   entries: [
//     {
//       id: "1A",
//       number: 1,
//       clue: "Prefix for some music genres",
//       direction: "across",
//       length: 3,
//       position: { row: 0, col: 0 },
//       solution: "ALT",
//     },
//     {
//       id: "4A",
//       number: 4,
//       clue: "Fab ___ (nickname for the Beatles)",
//       direction: "across",
//       length: 4,
//       position: { row: 1, col: 0 },
//       solution: "FOUR",
//     },
//     {
//       id: "6A",
//       number: 6,
//       clue: "Eagle's claw",
//       direction: "across",
//       length: 5,
//       position: { row: 2, col: 0 },
//       solution: "TALON",
//     },
//     {
//       id: "8A",
//       number: 8,
//       clue: "Fab ___ (nickname for a noted University of Michigan basketball team)",
//       direction: "across",
//       length: 4,
//       position: { row: 3, col: 1 },
//       solution: "FIVE",
//     },
//     {
//       id: "9A",
//       number: 9,
//       clue: "Congregant's seat",
//       direction: "across",
//       length: 3,
//       position: { row: 4, col: 2 },
//       solution: "PEW",
//     },
//     {
//       id: "1D",
//       number: 1,
//       clue: "Boat's rear",
//       direction: "down",
//       length: 3,
//       position: { row: 0, col: 0 },
//       solution: "AFT",
//     },
//     {
//       id: "2D",
//       number: 2,
//       clue: "Shape of a cat with its legs tucked under itself",
//       direction: "down",
//       length: 4,
//       position: { row: 0, col: 1 },
//       solution: "LOAF",
//     },
//     {
//       id: "3D",
//       number: 3,
//       clue: "Flower that's the subject of Dutch festivals",
//       direction: "down",
//       length: 5,
//       position: { row: 0, col: 2 },
//       solution: "TULIP",
//     },
//     {
//       id: "5D",
//       number: 5,
//       clue: "Wander aimlessly",
//       direction: "down",
//       length: 4,
//       position: { row: 1, col: 3 },
//       solution: "ROVE"
//     },
//     {
//       id: "7D",
//       number: 7,
//       clue: "Like many shows at the top of the Netflix queue",
//       direction: "down",
//       length: 3,
//       position: { row: 2, col: 4 },
//       solution: "NEW",
//     }
//   ],
// };

crossword.data = {
  id: "crosswords/example/thanksgiving",
  title: "Thanksgiving Mini",
  size: "8x7",
  entries: [
    {
      id: "1A",
      number: 1,
      clue: "Enjoyed a Thanksgiving meal",
      direction: "across",
      length: 7,
      position: { row: 0, col: 0 },
      solution: "FEASTED",
    },
    {
      id: "8A",
      number: 8,
      clue: "Back half of a GOAT?",
      direction: "across",
      length: 7,
      position: { row: 1, col: 0 },
      solution: "ALLTIME",
    },
    {
      id: "9A",
      number: 9,
      clue: "Sudden urge",
      direction: "across",
      length: 7,
      position: { row: 2, col: 0 },
      solution: "IMPULSE",
    },
    {
      id: "10A",
      number: 10,
      clue: "Santa's landing place",
      direction: "across",
      length: 4,
      position: { row: 3, col: 0 },
      solution: "ROOF",
    },
    {
      id: "11A",
      number: 11,
      clue: "Abstain from eating",
      direction: "across",
      length: 4,
      position: { row: 4, col: 3 },
      solution: "FAST",
    },
    {
      id: "15A",
      number: 15,
      clue: "Tough guy",
      direction: "across",
      length: 7,
      position: { row: 5, col: 0 },
      solution: "BRUISER",
    },
    {
      id: "18A",
      number: 18,
      clue: "Ready to use without further assembly",
      direction: "across",
      length: 7,
      position: { row: 6, col: 0 },
      solution: "TURNKEY",
    },
    {
      id: "19A",
      number: 19,
      clue: "Some pieces of [circled letters] at the Thanksgiving table",
      direction: "across",
      length: 5,
      position: { row: 7, col: 0 },
      solution: "WINGS",
    },
    {
      id: "1D",
      number: 1,
      clue: "Inside the foul line, in baseball",
      direction: "down",
      length: 4,
      position: { row: 0, col: 0 },
      solution: "FAIR",
    },
    {
      id: "2D",
      number: 2,
      clue: "Furry monster with a falsetto",
      direction: "down",
      length: 4,
      position: { row: 0, col: 1 },
      solution: "ELMO",
    },
    {
      id: "3D",
      number: 3,
      clue: "Pet food brand",
      direction: "down",
      length: 4,
      position: { row: 0, col: 2 },
      solution: "ALPO",
    },
    {
      id: "4D",
      number: 4,
      clue: "Thanksgiving side dish that can fill the [circled letters]",
      direction: "down",
      length: 8,
      position: { row: 0, col: 3 },
      solution: "STUFFING",
    },
    {
      id: "5D",
      number: 5,
      clue: "Shop ___ you drop",
      direction: "down",
      length: 3,
      position: { row: 0, col: 4 },
      solution: "TIL",
    },
    {
      id: "6D",
      number: 6,
      clue: "M M M M",
      direction: "down",
      length: 3,
      position: { row: 0, col: 5 },
      solution: "EMS",
    },
    {
      id: "7D",
      number: 7,
      clue: 'Billy ___ Williams, actor who played Lando Calrissian in "Star Wars"',
      direction: "down",
      length: 3,
      position: { row: 0, col: 6 },
      solution: "DEE",
    },
    {
      id: "12D",
      number: 12,
      clue: "Requests",
      direction: "down",
      length: 4,
      position: { row: 4, col: 4 },
      solution: "ASKS",
    },
    {
      id: "13D",
      number: 13,
      clue: '"Get what I\'m saying?"',
      direction: "down",
      length: 3,
      position: { row: 4, col: 5 },
      solution: "SEE",
    },
    {
      id: "14D",
      number: 14,
      clue: "Give it a go",
      direction: "down",
      length: 3,
      position: { row: 4, col: 6 },
      solution: "TRY",
    },
    {
      id: "15D",
      number: 15,
      clue: '"I should mention ...," for short',
      direction: "down",
      length: 3,
      position: { row: 5, col: 0 },
      solution: "BTW",
    },
    {
      id: "16D",
      number: 16,
      clue: "N.B.A. power forward ___ Hachimura",
      direction: "down",
      length: 3,
      position: { row: 5, col: 1 },
      solution: "RUI",
    },
    {
      id: "17D",
      number: 17,
      clue: "Large coffee dispenser",
      direction: "down",
      length: 3,
      position: { row: 5, col: 2 },
      solution: "URN",
    },
  ],
};

document.body.appendChild(crossword);
